services:
  # Auth Service (9000)
  auth-service:
    build:
      context: ./packages/guard-auth
      dockerfile: Dockerfile
    container_name: crm_auth
    restart: unless-stopped
    ports:
      - "9000:9000"
    env_file: .env
    depends_on:
      - kafka
    networks:
      - crm_network

  analytics-service:
    build:
      context: ./packages/analytics-service
    container_name: analytics-service
    environment:
      - NODE_ENV=production
      - KAFKA_BROKER=host.docker.internal:9092  # Указываем на host машину
      - MONGO_URL=${MONGO_URI}
      - REDIS_URL=redis://${REDIS_USERNAME}:${REDIS_PASSWORD}@${REDIS_HOST}:${REDIS_PORT}
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Для доступа к Kafka на host
    networks:
      - app-network
    restart: unless-stopped

  shift-service:
    build:
      context: ./packages/shift-service
    container_name: shift-service
    environment:
      - NODE_ENV=production
      - KAFKA_BROKER=host.docker.internal:9092
      - MONGO_URL=${MONGO_URI}
      - REDIS_URL=redis://${REDIS_USERNAME}:${REDIS_PASSWORD}@${REDIS_HOST}:${REDIS_PORT}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app-network
    restart: unless-stopped


  # Assigner Service (9003)
  assigner-service:
    build:
      context: ./packages/assigner
      dockerfile: Dockerfile
    container_name: crm_assigner
    restart: unless-stopped
    ports:
      - "9003:9003"
    env_file: .env
    depends_on:
      - kafka
    networks:
      - crm_network

  # Gateway (8000)
  gateway:
    build:
      context: ./shared
      dockerfile: Dockerfile
    container_name: crm_gateway
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - auth-service
      - shift-service
      - analytics-service
      - assigner-service
      - kafka
    networks:
      - crm_network

  # CRM Frontend (3001)
  crm:
    build:
      context: ./packages/crm
      dockerfile: Dockerfile
    container_name: crm_frontend
    restart: unless-stopped
    ports:
      - "3001:3001"
    env_file: .env
    depends_on:
      - gateway
    networks:
      - crm_network
    healthcheck:
      test: [ "CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3001/health" ]
      interval: 30s
      timeout: 3s
      retries: 3

volumes:
  zookeeper_data:
  kafka_data:

networks:
  crm_network:
    driver: bridge
